### PR TITLE
Updated to linux-3.14.77 and added optional aufs

### PR DESCRIPTION
**Pull request by cargoudel**
Need to run latest kernel for security certifications required by customer 

Basic testing done. 
git cherrypick'ed to commits over to 7600 branch
and tested xuart , ethernet , and usb on 7600

### CODE REVIEW

**Comment by cargoudel** [comment]
3.14.79 is expected to be the last update to the official 3.14 series kernel. 
This may be a good time to merge this patch.

**Comment by cargoudel** [comment]
@ts-kris any luck on your testing of this. Did you run in to any issues on your side?

**Comment by ts-kris** [comment]
@cargoudel Unfortunately no.  I had done some testing on the previous request, however it had been changed and I have not had time to address it again since then.  I still have this in my to do list and will get to it as soon as I can.

**Comment by cargoudel** [comment]
@ts-kris I know you are probably as busy as me, but I was wondering if you were still considering this pull request. Have you had any issues?

**Comment by ts-kris** [comment]
Sorry for the delay in comment, I've been out of office.

We have not had any issues so far, but we have also not had a lot of time for testing.  There are another couple of changes pending that may not require an image release, we are considering creating a new branch of the repo that adds these changes as well as your PR.

**Comment by cargoudel** [comment]
Updated and tested with latest upstream changes on the 7600.

**Comment by ts-kris** [comment]
These updates merged in to branch "linux-3.14.79-master" that is branched from the master branch.

These updates also merged in to branch "linux-3.14.79-7600-4600" which is branched from the 7600-4600 branch.  Additionally added AUFS support to the ts7600_defconfig, and updated the initramfs.cpio to auto-enable AUFS for the whole rootfs when FPGA soft jumper 4 is set (tshwctl --setjp 4).

**Pull request closed without merging**
